### PR TITLE
Document our decision to ignore tool specific configuration files

### PR DESCRIPTION
**Pull request by joshuagl**
We are opting to ignore tool specific configuration files which may exist in
the repository and only use configuration which has been set in precaution.json

This strategy allows us to expose relevant functionality common to all
supported linters in a consistent fashion. Furthermore by not exposing tool
specific configuration via Precaution we don't have to worry about migration
paths should we choose to change the underlying tools in future.

Closes: #81

Signed-off-by: Joshua Lock <jlock@vmware.com>

### CODE REVIEW

**Comment by MVrachev** [comment]
Maybe it won't be a bad idea to update the architecture in this pr given that we are saying that we hide the complexity of the underlying linters?

**Comment by joshuagl** [comment]
> Maybe it won't be a bad idea to update the architecture in this pr given that we are saying that we hide the complexity of the underlying linters?

We're explicitly hiding the complexity of the underlying linters from users, not developers. We should abstract the linters in the diagram as previously discussed, but I don't think it needs to happen in this PR?

**Comment by MVrachev** [comment]
> > Maybe it won't be a bad idea to update the architecture in this pr given that we are saying that we hide the complexity of the underlying linters?
> 
> We're explicitly hiding the complexity of the underlying linters from users, not developers. We should abstract the linters in the diagram as previously discussed, but I don't think it needs to happen in this PR?

Ookay, we can use another pr for that.
I think that this text should be added in a future doc for the configuration options.
Maybe we can keep it both places?

**Comment by joshuagl** [comment]
Agreed, I wanted to document the decision we made and prompt a GitHub Pages build by updating a file in docs. When we document our configuration we should include some user-focused text around this too.

**Comment by joshuagl** [comment]
Rebasing the branch to integrate the latest changes from the master branch dismissed the review.

**Pull request merged**
