### PR TITLE
Add logo to README

### PR DESCRIPTION
**Pull request by ericwb**
The project is in dire need of a logo. Here is one, approved by
brand.

Signed-off-by: Eric Brown <browne@vmware.com>

### CODE REVIEW

**Comment by MVrachev** [comment]
I like it.

**Comment by joshuagl** [comment]
Trying to prompt Travis with a close/reopen

**Comment by joshuagl** [comment]
Do your thing, Travis

**Comment by joshuagl** [comment]
Something has fallen out of synch with the Checks and the Status of the Travis build 😕

**Comment by ericwb** [comment]
Travis-CI is still not working

**Comment by joshuagl** [comment]
> Travis-CI is still not working

It's not clear to me what broke things but we don't seem to be receiving Checks API events from Travis CI.

**Pull request merged**
