### PR TITLE
Add Gif to the README

### PR DESCRIPTION
**Pull request by MVrachev**
It will be really useful if we add a GIF to the Precaution README.
That way we would show how Precaution works in 17 seconds!

Closes: https://github.com/vmware/precaution/issues/106

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

### CODE REVIEW

**Comment by joshuagl** [comment]
[ImageOptim](https://imageoptim.com/mac) wraps a bunch of image compression tools in a macOS GUI

**Comment by MVrachev** [comment]
I tried to export all images in 720 p, them I used ImageOptim as @joshuagl  suggested and in the end I combined them with gifsky. On Gifsky I set it with quality of 50 %.
The result is blurred Gif which is 30 mb in size.

I don't know how to shrink it more.

**Comment by joshuagl** [comment]
As the Gif is so large and adding large binaries to a git repo isn't good practice, can we instead upload the video to YouTube or similar and embed it in the README?

**Comment by ericwb** [comment]
How about using git-lfs for this file?

https://help.github.com/en/articles/collaboration-with-git-large-file-storage
https://help.github.com/en/articles/configuring-git-large-file-storage

**Comment by joshuagl** [comment]
This does seem like a good use-case for Git LFS, we gain the benefits of a Gif embedded in the README without having to worry about the impact of a large file on our git repository.

**Pull request closed without merging**
