### PR TITLE
Validation of the Go files

### PR DESCRIPTION
**Pull request by MVrachev**
This is a fix for this problem: https://github.com/vmware/precaution/issues/57

I wanted to make sure that Gosec will analyze valid Go files. The least thing I can do is to make sure that the file starts with a "package" statement as said here:
https://golang.org/doc/code.html#PackageNames

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

### CODE REVIEW

**Comment by evqna** [comment]
I also don't see how that solves our problem, shouldn't we just make sure our test files are well formed?

**Comment by MVrachev** [comment]
If we decide we don't have to check if the files are valid then we should make your test files: gofile1, gofile2 valid.
Antoine can you help with that?

**Comment by evqna** [comment]
Sure, I will see what I can do.

**Comment by evqna** [comment]
Solved in #76

**Pull request closed without merging**
