### PR TITLE
Enable Mergify for automatic merges

### PR DESCRIPTION
**Pull request by ericwb**
The Mergify GitHub App is already installed to the Precaution
repo.  This commit enables the app by setting necessary configuration
via the YAML file.

Note that this config sets the following conditions
- The number of approved code reviews must be 1 or greater
- The Travis CI must pass
- Enabled on branch master only
- Don't merge PRs with work-in-progress label
- And finally, only merge with label ready-to-merge

https://doc.mergify.io

Signed-off-by: Eric Brown <browne@vmware.com>

### CODE REVIEW

**Comment by MVrachev** [comment]
What if there are multiple commits into the pull request then what message will be merged? 
The message of the first commit? All messages from all commit related to the pr?

**Comment by joshuagl** [comment]
I like the idea of having an explicit label to tag the PR author is ready to have their work merged (and a separate explicit label to indicate something really isn't ready), it's worth noting however the [GitHub help pages](https://help.github.com/en/articles/about-labels) indicate that only those with write access to the repo can apply a label.

**Comment by joshuagl** [comment]
> What if there are multiple commits into the pull request then what message will be merged?
> The message of the first commit? All messages from all commit related to the pr?

The configuration is to use a rebase, thus all of the commits in the PR will be applied on top of the master branch. It would be good practice to only apply the "ready-to-merge" label once the request submitter has squashed their commits as desired.

It would be good to update CONTRIBUTING.md before we land this change.

**Comment by ericwb** [comment]
@MVrachev So yes, this app would merge using rebase first and squash as a backup.  I assume for the squash it preserves all commit messages.

@joshuagl Yep, the ready-to-merge would be used for the maintainers to use to finalize a PR ready to be merged.  So if one maintainer approved, but wanted a second opinion, he/she would have that option.  I definitely think the contributing doc could use a lot of updates.  I don't mind adding something in the doc about Mergify, but I'm not familiar enough how well it will work yet.  So might be better to update the doc in a separate PR

**Comment by joshuagl** [comment]
I'm OK with CONTRIBUTING in a separate PR.

**Comment by MVrachev** [comment]
So, if I understand correctly the pr workflow will be the following:
1) I open pr for a review
2) we review the code
3) you give me approval
4) I tag the pr with "ready-to-merge" label
5) the pr will be automatically merged

**Comment by MVrachev** [comment]
Another question is can we make Mergify to use only the pr message or first commit message for the commit which will be merged?

**Comment by ericwb** [comment]
@MVrachev In your PR workflow, which would be for any user (even maintainers), you wouldn't self mark the label of ready-to-merge.  That is for approvers.  If your PR is not ready, use work-in-progress or PR Drafts.

And to my knowledge, there is no way to configure Mergify to use just the first commit message.  Of course you can also squash your commits yourself using git, which is probably better practice anyway.

**Comment by joshuagl** [comment]
Looks good to me, let's rebase and merge.

**Pull request merged**
