### PR TITLE
WIP Correct links

### PR DESCRIPTION
**Pull request by MVrachev**
Use markdown format for links in README.

### CODE REVIEW

**Comment by MVrachev** [comment]
I am not sure how can I do those links in the docs to be clickable:
image

**Comment by ericwb** [comment]
Is this ready or still WIP?

**Comment by MVrachev** [comment]
Well, yes. This commit doesn't fix the links. I am not sure how to fix that thing.

**Comment by MVrachev** [comment]
We have the same problem in our initial setup documentation: 
image

**Pull request closed without merging**
