### PR TITLE
Minor documentation tweaks

### PR DESCRIPTION
**Pull request by joshuagl**
A couple of minor docs tweaks laying the groundwork for documenting the TSLint addition

### CODE REVIEW

**Comment by MVrachev** [comment]
Good changes.
It's a good idea if you squash the commits.
Besides that it's a great addtiion.

**Comment by joshuagl** [comment]
Happy to squash the commits into an "Improve documentation formatting" (or similar) if you feel that's better. 
It does seem to me that these are two distinct changes and therefore appropriate as two patches - I wouldn't squash two distinct code changes into one patch and I think the same rules should be applied to all changes to a repo.

**Comment by MVrachev** [comment]
Yes, you are right. I didn't look closely at the changes separately by the commits.

**Comment by joshuagl** [comment]
Force pushed to fix a typo in a commit message.

**Pull request merged**
